#!/bin/bash
FILE_NAME=$(echo $0 | awk -F/ '{print $NF}')

if [[ $FILE_NAME == "soundboard" ]]; then
  echo "Terminal Soundboard"
  echo "Play Sounds From your Terminal!"
  echo "Available sounds:"
  ls "$HOME/.local/share/soundboard"
  exit 0
fi


pw-cat --playback "$HOME/.local/share/soundboard/$FILE_NAME"
